// Code generated by protoc-gen-go. DO NOT EDIT.
// source: categorysplitfile.proto

/*
Package categorysplit is a generated protocol buffer package.

It is generated from these files:
	categorysplitfile.proto

It has these top-level messages:
	CategorySplitFile
*/
package categorysplit

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CategorySplitFile struct {
	TableId   int64  `protobuf:"varint,1,opt,name=table_id,json=tableId" json:"table_id,omitempty"`
	FileId    int64  `protobuf:"varint,2,opt,name=file_id,json=fileId" json:"file_id,omitempty"`
	Lines     int64  `protobuf:"varint,3,opt,name=lines" json:"lines,omitempty"`
	StartLine int64  `protobuf:"varint,4,opt,name=startLine" json:"startLine,omitempty"`
	Data      []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *CategorySplitFile) Reset()                    { *m = CategorySplitFile{} }
func (m *CategorySplitFile) String() string            { return proto.CompactTextString(m) }
func (*CategorySplitFile) ProtoMessage()               {}
func (*CategorySplitFile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CategorySplitFile) GetTableId() int64 {
	if m != nil {
		return m.TableId
	}
	return 0
}

func (m *CategorySplitFile) GetFileId() int64 {
	if m != nil {
		return m.FileId
	}
	return 0
}

func (m *CategorySplitFile) GetLines() int64 {
	if m != nil {
		return m.Lines
	}
	return 0
}

func (m *CategorySplitFile) GetStartLine() int64 {
	if m != nil {
		return m.StartLine
	}
	return 0
}

func (m *CategorySplitFile) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CategorySplitFile)(nil), "categorysplit.CategorySplitFile")
}

func init() { proto.RegisterFile("categorysplitfile.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4f, 0x4e, 0x2c, 0x49,
	0x4d, 0xcf, 0x2f, 0xaa, 0x2c, 0x2e, 0xc8, 0xc9, 0x2c, 0x49, 0xcb, 0xcc, 0x49, 0xd5, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x45, 0x91, 0x50, 0xea, 0x67, 0xe4, 0x12, 0x74, 0x86, 0x8a, 0x04,
	0x83, 0x44, 0xdc, 0x32, 0x73, 0x52, 0x85, 0x24, 0xb9, 0x38, 0x4a, 0x12, 0x93, 0x72, 0x52, 0xe3,
	0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0xd8, 0xc1, 0x7c, 0xcf, 0x14, 0x21, 0x71,
	0x2e, 0x76, 0x90, 0x69, 0x20, 0x19, 0x26, 0xb0, 0x0c, 0x1b, 0x88, 0xeb, 0x99, 0x22, 0x24, 0xc2,
	0xc5, 0x9a, 0x93, 0x99, 0x97, 0x5a, 0x2c, 0xc1, 0x0c, 0x16, 0x86, 0x70, 0x84, 0x64, 0xb8, 0x38,
	0x8b, 0x4b, 0x12, 0x8b, 0x4a, 0x7c, 0x32, 0xf3, 0x52, 0x25, 0x58, 0xc0, 0x32, 0x08, 0x01, 0x21,
	0x21, 0x2e, 0x96, 0x94, 0xc4, 0x92, 0x44, 0x09, 0x56, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x30, 0x3b,
	0x89, 0x0d, 0xec, 0x4e, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x2f, 0x7e, 0x5b, 0xc2,
	0x00, 0x00, 0x00,
}
