
create table if not exists EDM.DATABASE_CONFIG(
  ID	BIGINT NOT NULL,
  CONNECTION_TYPE	VARCHAR(255) NULL,
  DATABASE_NAME	VARCHAR(255) NOT NULL,
  DB_GROUP	VARCHAR(255) NOT NULL,
  HOST	VARCHAR(255) NOT NULL,
  NAME	VARCHAR(255) NOT NULL,
  PASSWORD	VARCHAR(255) NOT NULL,
  PORT	INTEGER NOT NULL,
  SCHEMA	VARCHAR(255) NOT NULL,
  TARGET	VARCHAR(255) NOT NULL,
  USERNAME	VARCHAR(255) NOT NULL,
  COMPANY	BIGINT  NULL,
  CONSTRAINT DATABASE_CONFIG_PK PRIMARY KEY (ID)
);

